version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: msb_postgres
    restart: always
    environment:
      POSTGRES_USER: msb_user
      POSTGRES_PASSWORD: msb_password
      POSTGRES_DB: msb_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: